spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/petpeers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  profiles:
    active:
    - default
#spring.jpa.show-sql: true